import { createRequire } from 'node:module';
import { mkdirSync, writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.SNOWBALL_PLAYWRIGHT_PATH || 'playwright');
const browser = await chromium.launch({ channel: process.env.SNOWBALL_BROWSER || 'msedge', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1050 } });
const page = await context.newPage();
const errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('console', message => { if (message.type() === 'error') errors.push(message.text() + ' ' + message.location().url); });
mkdirSync('test-results', { recursive: true });
try {
  await page.goto(process.env.SNOWBALL_URL || 'http://localhost:5173', { waitUntil: 'networkidle' });
  await page.waitForFunction(() => window.__snowball?.scene.isActive('Menu'));
  await page.screenshot({ path: 'test-results/title.png', fullPage: true });
  console.log('TITLE', JSON.stringify(errors));
  await page.keyboard.press('Enter');
  await page.waitForFunction(() => window.__snowball?.scene.isActive('Home'));
  await page.waitForTimeout(900);
  console.log('STATE', await page.evaluate(() => { const s=window.__snowball.scene.getScene('Home'); return {mode:s.mode, x:s.player.x,y:s.player.y,bodyY:s.player.body.y,grounded:s.player.grounded}; }));
  await page.screenshot({ path: 'test-results/home-intro.png', fullPage: true });
  await page.keyboard.press('KeyE'); await page.waitForTimeout(100); await page.keyboard.press('KeyE');
  await page.waitForTimeout(300);
  const before = await page.evaluate(() => window.__snowball.scene.getScene('Home').player.x);
  await page.keyboard.down('ArrowRight'); await page.waitForTimeout(1100); await page.keyboard.up('ArrowRight');
  await page.waitForTimeout(250);
  console.log('MOVE', await page.evaluate(() => {const s=window.__snowball.scene.getScene('Home'); return {x:s.player.x,y:s.player.y,fish:s.fish,mode:s.mode};}));
  const after = await page.evaluate(() => window.__snowball.scene.getScene('Home').player.x);
  assert(after > before + 100, 'Keyboard movement must advance player');
  assert.equal(await page.evaluate(() => window.__snowball.scene.getScene('Home').fish), 2, 'Walk-through fish must collect');
  await page.screenshot({ path: 'test-results/home.png', fullPage: true });
  const state = () => page.evaluate(() => {
    const s = window.__snowball.scene.getScene('Home');
    return { x:s.player.x,y:s.player.y,vy:s.player.body.velocity.y,grounded:s.player.grounded,fish:s.fish,stars:s.stars,feathers:s.feathers,hearts:s.hearts,mode:s.mode,flags:JSON.parse(localStorage.getItem('snowball-quest-save-v1')).run.flags };
  });
  const place = async (x,y) => { await page.evaluate(([x,y]) => {const s=window.__snowball.scene.getScene('Home');s.player.respawn(x,y);}, [x,y]); await page.waitForTimeout(180); };
  const closeDialogue = async () => { for(let i=0;i<5 && (await state()).mode==='dialogue';i++){await page.keyboard.press('KeyE');await page.waitForTimeout(80);} };
  const interact = async (x,y=640) => { await place(x,y);await page.keyboard.press('KeyE');await page.waitForTimeout(100);await closeDialogue(); };
  // Real keyboard jump must reach the first shelf from the floor.
  await place(430,640); await page.keyboard.down('ArrowRight'); await page.keyboard.down('Space');
  await page.waitForTimeout(490); await page.keyboard.up('ArrowRight'); await page.waitForTimeout(120); await page.keyboard.up('Space'); await page.waitForTimeout(250);
  assert((await state()).y <= 577, 'Jump and one-way platform landing must work');
  const dashStart = (await state()).x; await page.keyboard.press('Shift'); await page.waitForTimeout(180);
  assert((await state()).x > dashStart + 35, 'Dash must move Snowball');
  await page.keyboard.press('Escape'); await page.waitForFunction(()=>window.__snowball.scene.getScene('Home').mode==='paused'); const pausedX=(await state()).x;
  await page.keyboard.down('ArrowRight'); await page.waitForTimeout(220); await page.keyboard.up('ArrowRight');
  assert.equal((await state()).x,pausedX,'Pause must stop movement');
  await page.screenshot({path:'test-results/pause.png',fullPage:true}); await page.keyboard.press('Escape'); await page.waitForFunction(()=>window.__snowball.scene.getScene('Home').mode==='playing');
  await place(3440,640);await page.keyboard.down('ArrowRight');await page.waitForTimeout(600);await page.keyboard.up('ArrowRight');
  assert((await state()).x<3490,'Locked balcony blocks passage');
  await interact(3500-42); assert(!(await state()).flags['balcony-open'],'Door cannot bypass prerequisites');
  await interact(1120); assert((await state()).flags['mouse-met']);
  await interact(1220); assert((await state()).flags['plush-carried']);
  await interact(1120); assert((await state()).flags['mouse-helped']);
  await interact(1520); assert((await state()).flags.scratched);
  await place(2000,375); assert((await state()).flags['key-found']);
  await place(2176,640); assert.equal((await state()).hearts,5);
  await interact(2352); assert((await state()).flags['box-open']); assert.equal((await state()).stars,1);
  await interact(2352); assert.equal((await state()).stars,1,'Toybox reward must not duplicate');
  await interact(664); assert((await state()).flags['secret-nook']);
  await place(912,340); assert.equal((await state()).feathers>=1,true);
  await place(2900,430); assert.equal((await state()).stars,2);
  const preFall=await state(); await place(2540,850); await page.waitForTimeout(180);
  assert(Math.abs((await state()).x-2176)<4,'Fall returns to saved checkpoint');
  assert.equal((await state()).hearts,preFall.hearts-1);
  const beforeRefresh=await state();await page.reload({waitUntil:'networkidle'});await page.waitForFunction(()=>window.__snowball?.scene.isActive('Menu'));
  await page.keyboard.press('Enter');await page.waitForFunction(()=>window.__snowball?.scene.isActive('Home'));await page.waitForTimeout(250);
  assert.equal((await state()).fish,beforeRefresh.fish); assert.equal((await state()).stars,2);
  assert((await state()).flags['box-open']);assert(Math.abs((await state()).x-2176)<4);
  await interact(3500-42); assert((await state()).flags['balcony-open']);
  await place(3720,640); await page.keyboard.down('Space'); await page.waitForTimeout(250); await page.keyboard.up('Space'); await page.waitForTimeout(500); assert.equal((await state()).stars,3);
  await place(3890,640); await page.waitForTimeout(400);assert.equal((await state()).mode,'complete');
  await page.screenshot({path:'test-results/stage-clear.png',fullPage:true});
  const completed=await page.evaluate(()=>JSON.parse(localStorage.getItem('snowball-quest-save-v1')));
  assert.equal(completed.stages.home.completed,true); assert.equal(completed.stages.home.stars,3);
  const canvas=await page.locator('canvas').boundingBox();
  await page.mouse.click(canvas.x+640*canvas.width/1280,canvas.y+510*canvas.height/720);await page.waitForTimeout(250);
  assert.equal((await state()).stars,0);assert.equal((await state()).hearts,5);
  assert.equal(await page.evaluate(()=>window.__snowball.scene.getScene('Home').elapsed<1000),true,'Replay resets elapsed');
  assert.deepEqual(errors, [], 'Browser must run without console/runtime errors');
  writeFileSync('test-results/browser.json', JSON.stringify({ errors, before, after, completed:completed.stages.home, checkedAt: new Date().toISOString() }, null, 2));
  console.log('PASS: keyboard move/jump/dash, platform landing, fish pickup, dialogue, pause, locked door, quest chain, checkpoint/fall, refresh persistence, all3 stars, stage clear, replay, no runtime errors');
} finally { await browser.close(); }
